### ISSUE TITLE
String session

### ISSUE THREAD

**Issue by naveenxd** [Achu2234/YuiMusic-Py-tgcalls#1]
I have generated string session from repl now in which var should I add the string session I got

Should I paste my string session in var named SESSION_NAME

**Comment by Achu2234** [comment]
copy pastw

**Comment by naveenxd** [comment]
> copy pastw

Bro I mean where should I add my string session

**Comment by Achu2234** [comment]
ok

**Comment by naveenxd** [comment]
> ok

Bro say where I should add my string session to make my bot work

**Comment by Achu2234** [comment]
Bro first say where u making bot railway or herku

**Comment by naveenxd** [comment]
> Bro first say where u making bot railway or herku

Railway

**Comment by Achu2234** [comment]
https://youtu.be/n_bOHgq6JVk
 
 
 see this vidio and make

**Comment by naveenxd** [comment]
.
